### ISSUE TITLE
error running locally - `{"errors":[{"position":["paginate","distinct","match"],"code":"invalid ref","description":"Ref refers to undefined index 'all-stream-languages'"}]}`,

### ISSUE THREAD

**Issue by wweevv-johndpope** [Plazide/programrs.live#2]
```

}
wait  - compiling...
event - compiled successfully
[BadRequest: invalid ref] {
  description: "Ref refers to undefined index 'all-stream-languages'",
  requestResult: RequestResult {
    method: 'POST',
    path: '',
    query: null,
    requestRaw: '{"paginate":{"distinct":{"match":{"index":"all-stream-languages"},"terms":[]}}}',
    requestContent: Expr { raw: [Object] },
    responseRaw: `{"errors":[{"position":["paginate","distinct","match"],"code":"invalid ref","description":"Ref refers to undefined index 'all-stream-languages'"}]}`,
    responseContent: { errors: [Array] },
    statusCode: 400,
    responseHeaders: [Object: null prototype] {
      ':status': 400,
      'x-txn-time': '1659316669159000',
      'x-compute-ops': '1',
      'x-read-ops': '0',
      'x-byte-read-ops': '0',
      'x-byte-write-ops': '0',
      'x-write-ops': '0',
      'x-query-time': '7',
      'x-query-bytes-in': '79',
      'x-query-bytes-out': '147',
      'x-storage-bytes-read': '0',
      'x-storage-bytes-write': '0',
      'x-txn-retries': '0',
      'x-faunadb-build': '22.05.01-2a409c4',
      'content-length': '147',
      'content-type': 'application/json;charset=utf-8',
      [Symbol(nodejs.http2.sensitiveHeaders)]: []
    },
    startTime: 1659316669141,
    endTime: 1659316669161
  }
}
```

been jumping around instructions - 
 got docker running locally - 
I ran yarn fauna - 
supposedly succeeded

(base) ➜  programrs.live git:(main) ✗ yarn fauna
yarn run v1.22.19
$ fgu
[success] updated schema
(node:47023) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
[success] successfully uploaded indexes
[success] successfully uploaded roles
[success] successfully uploaded functions
[success] generated GraphQL types, queries and mutations
✨  Done in 4.99s.

I check the 

does it need some initial data? could I just hot wire this to "en" I wonder...

**Comment by Plazide** [comment]
Hey,

This issue is probably due to an outdated version of Fauna GQL Upload. Previous versions didn't consider invalid references, such as when a function references an index that doesn't exist yet. I haven't updated this project in a while, so it still uses an older version. Updating to the latest version should fix it.

Also, to populate the database, make a request to `/api/streams` while running the dev server.

**Comment by wweevv-johndpope** [comment]
thank you

**Comment by wweevv-johndpope** [comment]
it didn't fix. I wonder if crafting the faunal sql  create statements would help get out of jail of this.

**Comment by wweevv-johndpope** [comment]
BEGIN - RAMBLINGS....(you can skip to bottom - as this includes stuff I fixed along the way)
in the savetoFauna - I printed out the streams


export async function saveToFauna(streams: NormalizedStream[]){
	console.log('streams:',streams);


<img width="1325" alt="Screen Shot 2022-08-11 at 8 05 45 pm" src="https://user-images.githubusercontent.com/109928647/184110782-32d3a371-a86a-4b34-a5ba-20bfbb06cba6.png">


I can see twitch - api keys correctly dug up stuff - but it's saying its unauthorized at some point, so no data is saving???

I'm using the correct the  FG key - 


.env
```
NEXT_PUBLIC_FAUNA_API_ENDPOINT=http://localhost:8443
NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://localhost:8084/graphql
NEXT_PUBLIC_GRAPHQL_KEY=secret

FGU_SECRET=fnAEttG-cIACABEadla9-7qcNnq8t3iJxiZrhwvC
FGU_API_ENDPOINT=http://localhost:8443
FGU_GRAPHQL_ENDPOINT=http://localhost:8084
```

I guess this is NEXT_PUBLIC_GRAPHQL_KEY is wrong somehow....
I wonder if it's because it's localhost not 0.0.0.0


fauna add-endpoint http://localhost:8443 --alias localhost --key secret
 
```javascript

[Unauthorized: unauthorized] {
  description: 'Unauthorized',
  requestResult: RequestResult {
    method: 'POST',
    path: '',
    query: null,
    requestRaw: '{"let":[{"documents":{"match":{"index":"list-streams"},"terms":[]}}],"in":{"do":[{"foreach":{"lambda":"stream","expr":{"let":[{"match":{"match":{"index":"stream-by-channel"},"terms":{"select":["channel"],"from":{"var":"stream"}}}}],"in":{"if":{"exists":{"var":"match"}},"then":{"update":{"select":"ref","from":{"get":{"var":"match"}}},"params":{"object":{"data":{"merge":{"var":"stream"},"with":{"object":{"startedAt":{"time":{"select":"startedAt","from":{"var":"stream"}}}}}}}}},"else":{"create":{"collection":"Stream"},"params":{"object":{"data":{"merge":{"var":"stream"},"with":{"object":{"startedAt":{"time":{"select":"startedAt","from":{"var":"stream"}}}}}}}}}}}},"collection":[{"object":{"service":"twitch","viewers":24,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_juliday97-274x148.jpg","link":"https://twitch.tv/줄리님","title":"Making a Mechanical Keyboard and a Synth in C. 🐶🦶","startedAt":"2022-08-11T09:32:15.000Z","channel":"줄리님","language":"ko","tech":[]}},{"object":{"service":"twitch","viewers":6,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mrmeltybrain-274x148.jpg","link":"https://twitch.tv/MrMeltyBrain","title":"✿ chat controlled games, music, and visuals ✿","startedAt":"2022-08-10T21:17:18.000Z","channel":"MrMeltyBrain","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":4,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_lurxx-274x148.jpg","link":"https://twitch.tv/Lurxx","title":"🔴🎮 Twitch Statistics 📊 👾","startedAt":"2022-08-09T15:12:00.000Z","channel":"Lurxx","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mazoviansociofreakonomics-274x148.jpg","link":"https://twitch.tv/MazovianSocioFreakonomics","title":"I do things with Machine Learning!","startedAt":"2022-08-10T13:48:20.000Z","channel":"MazovianSocioFreakonomics","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_abidcasta-274x148.jpg","link":"https://twitch.tv/AbidCasta","title":"Impresion del Batarang!","startedAt":"2022-08-11T07:33:26.000Z","channel":"AbidCasta","language":"es","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_binarystate-274x148.jpg","link":"https://twitch.tv/BinaryState","title":"Technological Singularity","startedAt":"2022-08-10T01:37:32.000Z","channel":"BinaryState","language":"en","tech":[]}}]},{"foreach":{"lambda":"doc","expr":{"if":{"any":{"map":{"lambda":"stream","expr":{"equals":[{"select":["channel"],"from":{"var":"stream"}},{"select":["data","channel"],"from":{"var":"doc"}}]}},"collection":[{"object":{"service":"twitch","viewers":24,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_juliday97-274x148.jpg","link":"https://twitch.tv/줄리님","title":"Making a Mechanical Keyboard and a Synth in C. 🐶🦶","startedAt":"2022-08-11T09:32:15.000Z","channel":"줄리님","language":"ko","tech":[]}},{"object":{"service":"twitch","viewers":6,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mrmeltybrain-274x148.jpg","link":"https://twitch.tv/MrMeltyBrain","title":"✿ chat controlled games, music, and visuals ✿","startedAt":"2022-08-10T21:17:18.000Z","channel":"MrMeltyBrain","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":4,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_lurxx-274x148.jpg","link":"https://twitch.tv/Lurxx","title":"🔴🎮 Twitch Statistics 📊 👾","startedAt":"2022-08-09T15:12:00.000Z","channel":"Lurxx","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mazoviansociofreakonomics-274x148.jpg","link":"https://twitch.tv/MazovianSocioFreakonomics","title":"I do things with Machine Learning!","startedAt":"2022-08-10T13:48:20.000Z","channel":"MazovianSocioFreakonomics","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_abidcasta-274x148.jpg","link":"https://twitch.tv/AbidCasta","title":"Impresion del Batarang!","startedAt":"2022-08-11T07:33:26.000Z","channel":"AbidCasta","language":"es","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_binarystate-274x148.jpg","link":"https://twitch.tv/BinaryState","title":"Technological Singularity","startedAt":"2022-08-10T01:37:32.000Z","channel":"BinaryState","language":"en","tech":[]}}]}},"then":null,"else":{"delete":{"select":"ref","from":{"var":"doc"}}}}},"collection":{"map":{"lambda":"ref","expr":{"get":{"var":"ref"}}},"collection":{"paginate":{"var":"documents"},"size":10000}}}]}}',
    requestContent: Expr { raw: [Object] },
    responseRaw: '{"errors":[{"code":"unauthorized","description":"Unauthorized"}]}',
    responseContent: { errors: [Array] },
    statusCode: 401,
    responseHeaders: [Object: null prototype] {
      ':status': 401,
      'www-authenticate': 'Basic realm="Unauthorized"',
      'x-txn-time': '1660211968202000',
      'x-faunadb-build': '22.05.01-2a409c4',
      'content-length': '65',
      'content-type': 'application/json;charset=utf-8',
      [Symbol(nodejs.http2.sensitiveHeaders)]: []
    },
    startTime: 1660211968112,
    endTime: 1660211968214
  }
}

```
UPDATE
- this is my yarn lock file
- https://gist.github.com/wweevv-johndpope/14f6ac1c53cf6c306744b2255f4730cd


Now after a restart - not seeing the auth error

I added this

```javascript

const client = createClient({
	url: graphqlEndpoint,
	fetchOptions: () => ({
		headers: {
			"Authorization": `Bearer ${secret}`
		}
	}),
	exchanges: [dedupExchange, cache,errorExchange({
		onError: error => {

		  console.log("👹  error:",error);
		  const isAuthError = error.graphQLErrors.some(e => e.extensions?.code === 'FORBIDDEN');
  
		  if (isAuthError) {
			console.log("👹  isAuthError");
		  }
		},
	  }), fetchExchange]
})



there is this 

```javascript

[BadRequest: invalid ref] {
  description: "Ref refers to undefined index 'list-streams'",
  requestResult: RequestResult {
    method: 'POST',
    path: '',
    query: null,
    requestRaw: '{"let":[{"documents":{"match":{"index":"list-streams"},"terms":[]}}],"in":{"do":[{"foreach":{"lambda":"stream","expr":{"let":[{"match":{"match":{"index":"stream-by-channel"},"terms":{"select":["channel"],"from":{"var":"stream"}}}}],"in":{"if":{"exists":{"var":"match"}},"then":{"update":{"select":"ref","from":{"get":{"var":"match"}}},"params":{"object":{"data":{"merge":{"var":"stream"},"with":{"object":{"startedAt":{"time":{"select":"startedAt","from":{"var":"stream"}}}}}}}}},"else":{"create":{"collection":"Stream"},"params":{"object":{"data":{"merge":{"var":"stream"},"with":{"object":{"startedAt":{"time":{"select":"startedAt","from":{"var":"stream"}}}}}}}}}}}},"collection":[{"object":{"service":"twitch","viewers":27,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_juliday97-274x148.jpg","link":"https://twitch.tv/줄리님","title":"Making a Mechanical Keyboard and a Synth in C. 🐶🦶","startedAt":"2022-08-11T09:32:15.000Z","channel":"줄리님","language":"ko","tech":[]}},{"object":{"service":"twitch","viewers":6,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mrmeltybrain-274x148.jpg","link":"https://twitch.tv/MrMeltyBrain","title":"✿ chat controlled games, music, and visuals ✿","startedAt":"2022-08-10T21:17:18.000Z","channel":"MrMeltyBrain","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":4,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_lurxx-274x148.jpg","link":"https://twitch.tv/Lurxx","title":"🔴🎮 Twitch Statistics 📊 👾","startedAt":"2022-08-09T15:12:00.000Z","channel":"Lurxx","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mazoviansociofreakonomics-274x148.jpg","link":"https://twitch.tv/MazovianSocioFreakonomics","title":"I do things with Machine Learning!","startedAt":"2022-08-10T13:48:20.000Z","channel":"MazovianSocioFreakonomics","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_abidcasta-274x148.jpg","link":"https://twitch.tv/AbidCasta","title":"Impresion del Batarang!","startedAt":"2022-08-11T07:33:26.000Z","channel":"AbidCasta","language":"es","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_binarystate-274x148.jpg","link":"https://twitch.tv/BinaryState","title":"Technological Singularity","startedAt":"2022-08-10T01:37:32.000Z","channel":"BinaryState","language":"en","tech":[]}}]},{"foreach":{"lambda":"doc","expr":{"if":{"any":{"map":{"lambda":"stream","expr":{"equals":[{"select":["channel"],"from":{"var":"stream"}},{"select":["data","channel"],"from":{"var":"doc"}}]}},"collection":[{"object":{"service":"twitch","viewers":27,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_juliday97-274x148.jpg","link":"https://twitch.tv/줄리님","title":"Making a Mechanical Keyboard and a Synth in C. 🐶🦶","startedAt":"2022-08-11T09:32:15.000Z","channel":"줄리님","language":"ko","tech":[]}},{"object":{"service":"twitch","viewers":6,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mrmeltybrain-274x148.jpg","link":"https://twitch.tv/MrMeltyBrain","title":"✿ chat controlled games, music, and visuals ✿","startedAt":"2022-08-10T21:17:18.000Z","channel":"MrMeltyBrain","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":4,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_lurxx-274x148.jpg","link":"https://twitch.tv/Lurxx","title":"🔴🎮 Twitch Statistics 📊 👾","startedAt":"2022-08-09T15:12:00.000Z","channel":"Lurxx","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_mazoviansociofreakonomics-274x148.jpg","link":"https://twitch.tv/MazovianSocioFreakonomics","title":"I do things with Machine Learning!","startedAt":"2022-08-10T13:48:20.000Z","channel":"MazovianSocioFreakonomics","language":"en","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_abidcasta-274x148.jpg","link":"https://twitch.tv/AbidCasta","title":"Impresion del Batarang!","startedAt":"2022-08-11T07:33:26.000Z","channel":"AbidCasta","language":"es","tech":[]}},{"object":{"service":"twitch","viewers":1,"thumbnail":"https://static-cdn.jtvnw.net/previews-ttv/live_user_binarystate-274x148.jpg","link":"https://twitch.tv/BinaryState","title":"Technological Singularity","startedAt":"2022-08-10T01:37:32.000Z","channel":"BinaryState","language":"en","tech":[]}}]}},"then":null,"else":{"delete":{"select":"ref","from":{"var":"doc"}}}}},"collection":{"map":{"lambda":"ref","expr":{"get":{"var":"ref"}}},"collection":{"paginate":{"var":"documents"},"size":10000}}}]}}',
    requestContent: Expr { raw: [Object] },
    responseRaw: `{"errors":[{"position":["let",0,"documents","match"],"code":"invalid ref","description":"Ref refers to undefined index 'list-streams'"}]}`,
    responseContent: { errors: [Array] },
    statusCode: 400,
    responseHeaders: [Object: null prototype] {
      ':status': 400,
      'x-txn-time': '1660213559407000',
      'x-compute-ops': '1',
      'x-read-ops': '0',
      'x-byte-read-ops': '0',
      'x-byte-write-ops': '0',
      'x-write-ops': '0',
      'x-query-time': '154',
      'x-query-bytes-in': '4845',
      'x-query-bytes-out': '137',
      'x-storage-bytes-read': '0',
      'x-storage-bytes-write': '0',
      'x-txn-retries': '0',
      'x-faunadb-build': '22.05.01-2a409c4',
      'content-length': '137',
      'content-type': 'application/json;charset=utf-8',
      [Symbol(nodejs.http2.sensitiveHeaders)]: []
    },
    startTime: 1660213559225,
    endTime: 1660213559414

```

UPDATE - 
now I'm confused -  I dropped into fauna shell to introspect stuff - and it's complaining there's no database - yet the command to create database says database exists....
<img width="922" alt="Screen Shot 2022-08-11 at 8 32 31 pm" src="https://user-images.githubusercontent.com/109928647/184115180-63213c5b-1c58-4243-bece-2126d45088db.png">

sorry rerunning 
**yarn fauna** fixed auth issues.

I can see the insert 

UPDATE
```
fauna list-databases --endpoint=localhost
listing databases
fauna-dev
fauna-dev2
```

I think basically the insert / create script for the fauna is broken...

but I'm not sure how to fix.


<img width="560" alt="Screen Shot 2022-08-11 at 8 53 03 pm" src="https://user-images.githubusercontent.com/109928647/184118278-87bc2146-e5b4-4c4b-889d-b56ae3504fa9.png">

I'm not sure fauna eval existed when you wrote this program - 
it seems like a shortcut to interact with fauna.

I look in the code - but there's not much aligning to **CreateCollection**
is
Create
<img width="970" alt="Screen Shot 2022-08-11 at 9 02 10 pm" src="https://user-images.githubusercontent.com/109928647/184119574-d036432d-fad8-487a-b24d-13cc3f68b842.png">

**Comment by chj-web** [comment]
Hey,

I'm glad you could resolve most of this yourself. Seems like the error related to creating the index at the end is because the `fauna shell --endpoint=localhost` is missing a database option. It should be `fauna shell <your-database> --endpoint=localhost`.

As for that last comment, we don't use `CreateCollection` because fauna creates collections specified in the GraphQL schema upon upload. That's why FGU uploads the the schema first, so that we won't get reference errors when creating other resources. The `Create()` call in `saveToFauna()` simply creates a new document in the `Stream` collection.

I interpret this as you got it working. Let me know if you have any other problems.

**Comment by wweevv-johndpope** [comment]
so for clarity - in the api / backend code - running on server (direct db access)
I saveToFauna (no error)

I immediately query the indexes 
```javascript
	let m = await client.query(
		q.Paginate(q.Indexes())
	)
	console.log("m:",m);
```
we're good - 
```javascript
m1: {
  data: [
    Index("all-stream-languages"),
    Index("all-stream-services"),
    Index("all-streams"),
    Index("list-streams"),
    Index("stream-by-channel"),
    Index("streams-by-startedAt-asc"),
    Index("streams-by-startedAt-desc"),
    Index("streams-by-viewers-asc"),
    Index("streams-by-viewers-desc")
  ]
}
```


in the frontend code - that's authenticating with public access to graphql endpoint - 

I change the code to simply return all the indexes - 
<img width="660" alt="Screen Shot 2022-08-17 at 2 08 59 pm" src="https://user-images.githubusercontent.com/109928647/185032825-d492c709-1686-4839-b5d3-4024a115b4ac.png">

finally an unobscured error message.
![Screen Shot 2022-08-17 at 2 10 11 pm](https://user-images.githubusercontent.com/109928647/185034037-151969de-a948-4f3d-b8ed-dd1a669e856c.png)


UPDATE - 
so it ended up being I had attemped to use NEXT_PUBLIC_GRAPHQL_KEY=secret but that threw the missing indexes - it should have really complained it was unauthorized - wow.
I'm finally up and running...
